version: '3.8'

services:
  postgres:
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 1G

  minio:
    restart: always
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
    deploy:
      resources:
        limits:
          memory: 1G

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
      args:
        - NODE_ENV=production
    restart: always
    environment:
      NODE_ENV: production
      PORT: ${BACKEND_PORT:-3000}
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      DB_SYNCHRONIZE: false
      DB_LOGGING: false
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION:-1d}
      CORS_ORIGIN: ${CORS_ORIGIN}
      S3_ENDPOINT: http://minio:9000
      S3_ACCESS_KEY: ${MINIO_ROOT_USER}
      S3_SECRET_KEY: ${MINIO_ROOT_PASSWORD}
      S3_BUCKET: ${S3_BUCKET:-legisflow}
    deploy:
      resources:
        limits:
          memory: 1G
    depends_on:
      - postgres
      - minio

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
      args:
        - NODE_ENV=production
    restart: always
    environment:
      NODE_ENV: production
      PORT: ${FRONTEND_PORT:-3001}
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    deploy:
      resources:
        limits:
          memory: 1G
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/www:/var/www/html
    depends_on:
      - backend
      - frontend
    deploy:
      resources:
        limits:
          memory: 512M

volumes:
  postgres_data:
  minio_data:

