version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: legisflow-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_DATABASE:-legisflow}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT:-5432}:5432"
    networks:
      - legisflow-network

  minio:
    image: minio/minio
    container_name: legisflow-minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
    volumes:
      - minio_data:/data
    ports:
      - "${MINIO_PORT:-9000}:9000"
      - "${MINIO_CONSOLE_PORT:-9001}:9001"
    command: server /data --console-address ":9001"
    networks:
      - legisflow-network

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
      target: builder
    container_name: legisflow-backend
    restart: unless-stopped
    depends_on:
      - postgres
      - minio
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      PORT: ${BACKEND_PORT:-3000}
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: ${DB_USERNAME:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
      DB_DATABASE: ${DB_DATABASE:-legisflow}
      DB_SYNCHRONIZE: ${DB_SYNCHRONIZE:-true}
      JWT_SECRET: ${JWT_SECRET:-your-secret-key}
      JWT_EXPIRATION: ${JWT_EXPIRATION:-1d}
      CORS_ORIGIN: ${CORS_ORIGIN:-*}
      S3_ENDPOINT: http://minio:9000
      S3_ACCESS_KEY: ${MINIO_ROOT_USER:-minioadmin}
      S3_SECRET_KEY: ${MINIO_ROOT_PASSWORD:-minioadmin}
      S3_BUCKET: ${S3_BUCKET:-legisflow}
    ports:
      - "${BACKEND_PORT:-3000}:3000"
    volumes:
      - ./backend:/app/backend
      - ./shared:/app/shared
      - /app/backend/node_modules
      - /app/shared/node_modules
    networks:
      - legisflow-network
    command: npm run dev:backend

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
      target: builder
    container_name: legisflow-frontend
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      PORT: ${FRONTEND_PORT:-3001}
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:3000/api}
    ports:
      - "${FRONTEND_PORT:-3001}:3001"
    volumes:
      - ./frontend:/app/frontend
      - ./shared:/app/shared
      - /app/frontend/node_modules
      - /app/shared/node_modules
    networks:
      - legisflow-network
    command: npm run dev:frontend

networks:
  legisflow-network:
    driver: bridge

volumes:
  postgres_data:
  minio_data:
