name: CI/CD Pipeline

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      # Build and push backend image
      - name: Build and push backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ vars.DOCKER_USER }}/legisflow-cemac-backend:latest
            ${{ vars.DOCKER_USER }}/legisflow-cemac-backend:${{ github.sha }}
          cache-from: type=registry,ref=${{ vars.DOCKER_USER }}/legisflow-cemac-backend:buildcache
          cache-to: ${{ github.event_name != 'pull_request' && format('type=registry,ref={0}/legisflow-cemac-backend:buildcache,mode=max', vars.DOCKER_USER) || '' }}
      
      # Build and push frontend image
      - name: Build and push frontend
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ vars.DOCKER_USER }}/legisflow-cemac-frontend:latest
            ${{ vars.DOCKER_USER }}/legisflow-cemac-frontend:${{ github.sha }}
          cache-from: type=registry,ref=${{ vars.DOCKER_USER }}/legisflow-cemac-frontend:buildcache
          cache-to: ${{ github.event_name != 'pull_request' && format('type=registry,ref={0}/legisflow-cemac-frontend:buildcache,mode=max', vars.DOCKER_USER) || '' }}
      
      # Build and push nginx image (for production)
      - name: Build and push nginx
        uses: docker/build-push-action@v6
        with:
          context: ./nginx
          file: ./nginx/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ vars.DOCKER_USER }}/legisflow-cemac-nginx:latest
            ${{ vars.DOCKER_USER }}/legisflow-cemac-nginx:${{ github.sha }}
          cache-from: type=registry,ref=${{ vars.DOCKER_USER }}/legisflow-cemac-nginx:buildcache
          cache-to: ${{ github.event_name != 'pull_request' && format('type=registry,ref={0}/legisflow-cemac-nginx:buildcache,mode=max', vars.DOCKER_USER) || '' }}

  # Add a job for testing if needed
  test:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: |
          npm ci
      
      - name: Run tests
        run: |
          npm test
          
      - name: Verify build
        run: |
          npm run build
